#inpackage: False
testonly: False
with-expecter: True
all: False
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
#mockname: "{{.InterfaceName}}"
#outpkg: "{{.PackageName}}"
#filename: "{{.InterfaceName}}.go"
packages:
  gmountie/pkg/server/service:
    config:
      recursive: true
      include-regex: ".*(Repository|Service)"
  gmountie/pkg/client/grpc:
    config:
      all: true
  gmountie/pkg/proto:
    config:
      all: true
  github.com/hanwen/go-fuse/v2/fuse/pathfs:
    interfaces:
      FileSystem:
  github.com/hanwen/go-fuse/v2/fuse/nodefs:
    interfaces:
      File:
