version: '3'

tasks:
  gen:grpc:
    cmds:
      - |
        protoc --go_out=. --go-grpc_out=. api/proto/*.proto

  gen:mocks:
    cmds:
      - rm -rf mocks
      - go run github.com/vektra/mockery/v2@v2.46.3

  test:
    cmds:
      - go test -v ./...

  test:coverage:
    cmds:
      - go test -count=1 -coverpkg=./... -covermode=atomic -coverprofile coverage.out  ./...
      - grep -v -E "gmountie/mocks|gmountie/test|gmountie/pkg/proto" coverage.out > coverage-filtered.out
      - mv coverage-filtered.out coverage.out



  build:server:
    cmds:
      - go build -o out/server cmd/server/main.go

