# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:

  ui:
    dir: ./ui
    taskfile: ./ui/Taskfile.yml
    optional: true


tasks:
  gen:grpc:
    cmds:
      - |
        protoc --go_out=. --go-grpc_out=. api/proto/*.proto

  gen:mocks:
    cmds:
      - rm -rf internal/mocks
      - go run github.com/vektra/mockery/v2@v2.46.3

  lint:
    cmds:
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint@latest run {{ .LINT_EXTRA_ARGS }} ./...

  test:
    cmds:
      - go test -failfast -v ./...

  test:coverage:
    cmds:
      - go test -v -count=1 -coverpkg=./... -covermode=atomic -coverprofile coverage.out  ./...
      - grep -v -E "gmountie/internal/mocks|gmountie/test|gmountie/pkg/proto" coverage.out > coverage-filtered.out
      - mv coverage-filtered.out coverage.out

  build:
    cmds:
      - goreleaser build --snapshot --clean

