apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gmountie-server.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    # This is the configuration file for gmountie-server
    # The configuration file is in YAML format
    server:
      address: 0.0.0.0
    volumes:
      - name: data
        path: /data
