apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  name: {{ include "gmountie-server.fullname" . }}
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: gmountie.home.buluba.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "gmountie-server.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - hosts:
        - gmountie.home.buluba.net
      secretName: gmountie-tls-cert
