apiVersion: v1
kind: Service
metadata:
  name: {{ include "gmountie-server.fullname" . }}
  labels:
    {{- include "gmountie-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "gmountie-server.selectorLabels" . | nindent 4 }}
