// Code generated by mockery v2.46.3. DO NOT EDIT.

package proto

import (
	context "context"
	proto "gmountie/pkg/proto"

	mock "github.com/stretchr/testify/mock"
)

// MockVolumeServiceServer is an autogenerated mock type for the VolumeServiceServer type
type MockVolumeServiceServer struct {
	mock.Mock
}

type MockVolumeServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVolumeServiceServer) EXPECT() *MockVolumeServiceServer_Expecter {
	return &MockVolumeServiceServer_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: _a0, _a1
func (_m *MockVolumeServiceServer) List(_a0 context.Context, _a1 *proto.VolumeListRequest) (*proto.VolumeListReply, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *proto.VolumeListReply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.VolumeListRequest) (*proto.VolumeListReply, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.VolumeListRequest) *proto.VolumeListReply); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.VolumeListReply)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.VolumeListRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVolumeServiceServer_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVolumeServiceServer_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *proto.VolumeListRequest
func (_e *MockVolumeServiceServer_Expecter) List(_a0 interface{}, _a1 interface{}) *MockVolumeServiceServer_List_Call {
	return &MockVolumeServiceServer_List_Call{Call: _e.mock.On("List", _a0, _a1)}
}

func (_c *MockVolumeServiceServer_List_Call) Run(run func(_a0 context.Context, _a1 *proto.VolumeListRequest)) *MockVolumeServiceServer_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*proto.VolumeListRequest))
	})
	return _c
}

func (_c *MockVolumeServiceServer_List_Call) Return(_a0 *proto.VolumeListReply, _a1 error) *MockVolumeServiceServer_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVolumeServiceServer_List_Call) RunAndReturn(run func(context.Context, *proto.VolumeListRequest) (*proto.VolumeListReply, error)) *MockVolumeServiceServer_List_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedVolumeServiceServer provides a mock function with given fields:
func (_m *MockVolumeServiceServer) mustEmbedUnimplementedVolumeServiceServer() {
	_m.Called()
}

// MockVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedVolumeServiceServer'
type MockVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedVolumeServiceServer is a helper method to define mock.On call
func (_e *MockVolumeServiceServer_Expecter) mustEmbedUnimplementedVolumeServiceServer() *MockVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call {
	return &MockVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedVolumeServiceServer")}
}

func (_c *MockVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call) Run(run func()) *MockVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call) Return() *MockVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call) RunAndReturn(run func()) *MockVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVolumeServiceServer creates a new instance of MockVolumeServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVolumeServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVolumeServiceServer {
	mock := &MockVolumeServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
