// Code generated by mockery v2.46.3. DO NOT EDIT.

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "gmountie/pkg/proto"
)

// MockVolumeServiceClient is an autogenerated mock type for the VolumeServiceClient type
type MockVolumeServiceClient struct {
	mock.Mock
}

type MockVolumeServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVolumeServiceClient) EXPECT() *MockVolumeServiceClient_Expecter {
	return &MockVolumeServiceClient_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx, in, opts
func (_m *MockVolumeServiceClient) List(ctx context.Context, in *proto.VolumeListRequest, opts ...grpc.CallOption) (*proto.VolumeListReply, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *proto.VolumeListReply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.VolumeListRequest, ...grpc.CallOption) (*proto.VolumeListReply, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.VolumeListRequest, ...grpc.CallOption) *proto.VolumeListReply); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.VolumeListReply)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.VolumeListRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVolumeServiceClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVolumeServiceClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.VolumeListRequest
//   - opts ...grpc.CallOption
func (_e *MockVolumeServiceClient_Expecter) List(ctx interface{}, in interface{}, opts ...interface{}) *MockVolumeServiceClient_List_Call {
	return &MockVolumeServiceClient_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockVolumeServiceClient_List_Call) Run(run func(ctx context.Context, in *proto.VolumeListRequest, opts ...grpc.CallOption)) *MockVolumeServiceClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.VolumeListRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockVolumeServiceClient_List_Call) Return(_a0 *proto.VolumeListReply, _a1 error) *MockVolumeServiceClient_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVolumeServiceClient_List_Call) RunAndReturn(run func(context.Context, *proto.VolumeListRequest, ...grpc.CallOption) (*proto.VolumeListReply, error)) *MockVolumeServiceClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVolumeServiceClient creates a new instance of MockVolumeServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVolumeServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVolumeServiceClient {
	mock := &MockVolumeServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
