// Code generated by mockery v2.46.3. DO NOT EDIT.

package service

import (
	service "gmountie/pkg/server/service"

	mock "github.com/stretchr/testify/mock"
)

// MockVolumeServiceOptions is an autogenerated mock type for the VolumeServiceOptions type
type MockVolumeServiceOptions struct {
	mock.Mock
}

type MockVolumeServiceOptions_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVolumeServiceOptions) EXPECT() *MockVolumeServiceOptions_Expecter {
	return &MockVolumeServiceOptions_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockVolumeServiceOptions) Execute(_a0 *service.VolumeServiceImpl) {
	_m.Called(_a0)
}

// MockVolumeServiceOptions_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockVolumeServiceOptions_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *service.VolumeServiceImpl
func (_e *MockVolumeServiceOptions_Expecter) Execute(_a0 interface{}) *MockVolumeServiceOptions_Execute_Call {
	return &MockVolumeServiceOptions_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockVolumeServiceOptions_Execute_Call) Run(run func(_a0 *service.VolumeServiceImpl)) *MockVolumeServiceOptions_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*service.VolumeServiceImpl))
	})
	return _c
}

func (_c *MockVolumeServiceOptions_Execute_Call) Return() *MockVolumeServiceOptions_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockVolumeServiceOptions_Execute_Call) RunAndReturn(run func(*service.VolumeServiceImpl)) *MockVolumeServiceOptions_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVolumeServiceOptions creates a new instance of MockVolumeServiceOptions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVolumeServiceOptions(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVolumeServiceOptions {
	mock := &MockVolumeServiceOptions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
