// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * Volume is a struct that contains information about a volume.
 */
export class Volume {
    "Name": string;

    /** Creates a new Volume instance. */
    constructor($$source: Partial<Volume> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Volume instance from a string or object.
     */
    static createFrom($$source: any = {}): Volume {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Volume($$parsedSource as Partial<Volume>);
    }
}
