// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LoginControllerImpl is an implementation of LoginController
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function IsLoggedIn(): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1905227692) as any;
    return $resultPromise;
}

export function Login(loginInfo: $models.LogInInfo): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3951458046, loginInfo) as any;
    return $resultPromise;
}

/**
 * Logout logs the user out
 */
export function Logout(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1633975615) as any;
    return $resultPromise;
}
