// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * LogInInfo is a struct that holds the login information
 */
export class LogInInfo {
    "Username": string;
    "Password": string;
    "Address": string;
    "Port": number;
    "TLS": boolean;

    /** Creates a new LogInInfo instance. */
    constructor($$source: Partial<LogInInfo> = {}) {
        if (!("Username" in $$source)) {
            this["Username"] = "";
        }
        if (!("Password" in $$source)) {
            this["Password"] = "";
        }
        if (!("Address" in $$source)) {
            this["Address"] = "";
        }
        if (!("Port" in $$source)) {
            this["Port"] = 0;
        }
        if (!("TLS" in $$source)) {
            this["TLS"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogInInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LogInInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogInInfo($$parsedSource as Partial<LogInInfo>);
    }
}
