image:
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 9449
  externalTrafficPolicy: Local

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: "rook-ceph-block"
