name: Release

on:
  push:
    tags:
      - '*'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache apt packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libwebkit2gtk-4.1-dev curl
        version: 1.0

    - name: Setup Go 1.23.0
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.0

    - name: Use Node.js '20.x'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        node-version-file: "ui/frontend/package.json"
        cache: npm
        cache-dependency-path: "ui/frontend/package-lock.json"

    - name: Install dependencies
      run: |
        go install github.com/go-task/task/v3/cmd/task
        go install github.com/wailsapp/wails/v3/cmd/wails

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

