name: Release

on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types:
      - completed
#  push:
#    tags:
#      - '**'
#    branches:
#      - master
jobs:
  appimage-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwebkit2gtk-4.1-dev curl
          version: 1.0
      - name: Setup Go 1.23.0
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - name: Use Node.js '20.x'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Build AppImage
        run: |
          task ui:build:appimage
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            ui/build/appimage/*.AppImage
