name: Release

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Build type'
        type: choice
        options:
          - 'production'
          - 'alpha'
          - 'snapshot'
        required: true
        default: 'snapshot'

permissions:
  contents: write
  packages: write

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Cache apt packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: fio libwebkit2gtk-4.1-dev gtk+-3.0
        version: 2.0

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Use Node.js '20.x'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: npm
        cache-dependency-path: "ui/frontend/package-lock.json"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Install dependencies
      run: |
        go install github.com/go-task/task/v3/cmd/task
        go install -v github.com/wailsapp/wails/v3/cmd/wails3@latest
        go install github.com/caarlos0/svu@latest

    - name: Tag Release (Production)
      if: ${{  github.event.inputs.type == 'production' }}
      run: |
        git tag "$(svu next)"

    - name: Tag Release (Alpha)
      if: ${{  github.event.inputs.type == 'alpha' }}
      run: |
        git tag "$(svu prerelease --pre-release alpha)"

    - name: Set release type
      if: ${{  github.event.inputs.type == 'snapshot' }}
      run: echo "flags=--snapshot" >> $GITHUB_ENV

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean ${{ env.flags }}
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Push Tags
      if: ${{  github.event.inputs.type == 'alpha' || github.event.inputs.type == 'production' }}
      run: git push --tags
