name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      snapshot:
        description: 'Create a snapshot release'
        required: true
        default: true
        type: boolean

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Cache apt packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: fio libwebkit2gtk-4.1-dev gtk+-3.0
        version: 2.0

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Use Node.js '20.x'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: npm
        cache-dependency-path: "ui/frontend/package-lock.json"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Install dependencies
      run: |
        go install github.com/go-task/task/v3/cmd/task
        go install -v github.com/wailsapp/wails/v3/cmd/wails3@latest

    - name: Set snapshot release
      if: ${{  github.event.inputs.snapshot == 'true' }}
      run: echo "flags=--snapshot" >> $GITHUB_ENV

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean ${{ env.flags }}
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

