// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVolumes() {
  return window['go']['main']['App']['GetVolumes']();
}

export function IsMounted(arg1) {
  return window['go']['main']['App']['IsMounted'](arg1);
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Mount(arg1) {
  return window['go']['main']['App']['Mount'](arg1);
}

export function Unmount(arg1) {
  return window['go']['main']['App']['Unmount'](arg1);
}
