// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';

export function GetVolumes():Promise<Array<common.Volume>>;

export function IsMounted(arg1:common.Volume):Promise<boolean>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function Logout():Promise<void>;

export function Mount(arg1:common.Volume):Promise<void>;

export function Unmount(arg1:common.Volume):Promise<void>;
